version: "3"

volumes:
  pg-boss-pgdata:

services:
  db:
    image: postgres:11-alpine
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - pg-boss-pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pgboss
      - POSTGRES_PASSWORD=postgres
